#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: Base/pose
        pose2d: Base/ground_pose
        child_frame_id: Base/base_link
        parent_frame_id: world
        use_new_coordinates: false
    '2':
        pose: Link_1/pose
        pose2d: Link_1/ground_pose
        child_frame_id: Link_1/base_link
        parent_frame_id: world
        use_new_coordinates: false
    '3':
        pose: Link_2/pose
        pose2d: Link_2/ground_pose
        child_frame_id: Link_2/base_link
        parent_frame_id: world
        use_new_coordinates: false
optitrack_config:
        multicast_address: 224.0.0.1
